AWSTemplateFormatVersion: '2010-09-09'

Description: Infraestructura DevOps basica

Resources:

  MiBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: devops-cf-bucket-fercepeda

  MiInstancia:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0c02fb55956c7d316
      InstanceType: t2.micro
